__default__ :
        job-name      : "{rule}"
        output        : "logs/{rule}/{wildcards}.out"
        ntasks        : 1
        cpus-per-task : 1
        mem           : "200M"
        time          : "00-00:05:00"
        gres          : null
        account       : "my_account"
        partition     : "my_partition"

# Override the above defaults with job specific values
#bwa_mem :
#        cpus-per-task : 16
#        mem           : "10000M"
#        time          : "00-01:00:00"

#fastqc_raw :
#	cpus-per-task  : 1
#	mem	       : "200M"
#	time           : "00-01:40:00"

# Job specific resource requirements can be passed from the rule, in the Snakefile, via the "resources" keyword

sequelTools :
        cpus-per-task : 1
        mem           : "3000"
        time          : "00-01:05:00"

#sambamba_random :
#        cpus-per-task : 10
#        mem           : "200"
#        time          : "00-00:15:00"

get_raw_length_distribution: 
        cpus-per-task : 1
        mem           : "3000"
        time          : "00-02:00:00"

samtools_fastq :
        cpus-per-task : 32
        mem           : "20000"
        time          : "00-05:00:00"

bam2fastq:
        cpus-per-task : 48
        mem           : "10000"
        time          : "00-05:00:00"

bbduk :
        cpus-per-task : 20
        mem           : "10000"
        time          : "00-00:40:00"

bbduk_genome :
        cpus-per-task : 20
        mem           : "10000"
        time          : "00-00:40:00"

#1 min for chloroplast/mitochondria
# way longer for genome
bbmap_sort:
        cpus-per-task : 1
        mem           : "70000"
        time          : "00-01:30:00"

select_longest:
        cpus-per-task : 1
        mem           : "3000"
        time          : "00-00:30:00"

filtlong:
        cpus-per-task : 1
        mem           : "5000"
        time          : "00-00:01:00"

#Seqtk subsets the reads to get the approximate desired coverage for the assembly
seqtk_genome: 
        cpus-per-task : 1
        mem           : "15000"
        time          : "00-00:40:00"

seqtk_mitochondria: 
        cpus-per-task : 1
        mem           : "100"
        time          : "00-00:02:00"

#Create assemblies using flye
flye_genome :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

flye :
        cpus-per-task : 1
        mem           : "1000"
        time          : "00-00:{resources.time}:00"

flye_mitochondria :
        cpus-per-task : 5
        mem           : "3000"
        time          : "00-00:15:00"

quast :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

quastref :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

minimap2_1:
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

racon_1:
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

raven :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

wtdbg2:
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

smartdenovo :
        cpus-per-task : 32
        mem           : "96000"
        time          : "01-00:00:00"

canu :
        cpus-per-task : 1
        mem           : "50"
        time          : "00-05:00:00"

mummer :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

busco :
        cpus-per-task : 10
        mem           : "30000"
        time          : "00-12:00:00"

gt_ltrharvest:
        cpus-per-task : 1
        mem           : "6000"
        time          : "00-09:30:00"

ltr_finder:
        cpus-per-task : 10
        mem           : "30000"
        time          : "00-00:20:00"

ltr_retriever:
        cpus-per-task : 10
        mem           : "30000"
        time          : "00-18:00:00"

#make_fofn :
#        cpus-per-task : 1
#        mem           : "20"
#        time          : "00-00:00:30"

#pb_falcon :
#        cpus-per-task : 1
#        mem           : "500"
#        time          : "00-00:30:00"
