__default__ :
        job-name      : "{rule}"
        output        : "logs/{rule}/{wildcards}.out"
        ntasks        : 1
        cpus-per-task : 1
        mem           : "200M"
        time          : "00-00:05:00"
        account       : "my_account"
        partition     : "my_partition"

# Override the above defaults with job specific values
#bwa_mem :
#        cpus-per-task : 16
#        mem           : "10000M"
#        time          : "00-01:00:00"

#fastqc_raw :
#	cpus-per-task  : 1
#	mem	       : "200M"
#	time           : "00-01:40:00"

# Job specific resource requirements can be passed from the rule, in the Snakefile, via the "resources" keyword

sequelTools :
        cpus-per-task : 1
        mem           : "3000"
        time          : "00-01:05:00"

#sambamba_random :
#        cpus-per-task : 10
#        mem           : "200"
#        time          : "00-00:15:00"

samtools_fastq :
        cpus-per-task : 32
        mem           : "20000"
        time          : "00-05:00:00"

bbduk :
        cpus-per-task : 20
        mem           : "10000"
        time          : "00-00:40:00"

bbmap_sort:
        cpus-per-task : 1
        mem           : "3000"
        time          : "00-00:01:00"

#Seqtk subsets the reads to get the approximate desired coverage for the assembly
seqtk_genome: 
        cpus-per-task : 1
        mem           : "2000"
        time          : "00-00:40:00"

seqtk_chloroplast: 
        cpus-per-task : 1
        mem           : "100"
        time          : "00-00:01:00"

seqtk_mitochondria: 
        cpus-per-task : 1
        mem           : "100"
        time          : "00-00:02:00"

#Create assemblies using flye
flye_genome :
        cpus-per-task : 15
        mem           : "15000"
        time          : "00-00:40:00"

flye :
        cpus-per-task : 10
        mem           : "15000"
        time          : "00-00:10:00"

flye_mitochondria :
        cpus-per-task : 5
        mem           : "3000"
        time          : "00-00:15:00"

quast :
        cpus-per-task : 1
        mem           : "200"
        time          : "00-00:01:00"


raven :
        cpus-per-task : 10
        mem           : "15000"
        time          : "00-00:10:00"

smartdenovo :
        cpus-per-task : 10
        mem           : "15000"
        time          : "00-00:10:00"

canu :
        cpus-per-task : 1
        mem           : "100"
        time          : "00-00:15:00"

mummer :
        cpus-per-task : 1
        mem           : "200"
        time          : "00-00:01:00"


#make_fofn :
#        cpus-per-task : 1
#        mem           : "20"
#        time          : "00-00:00:30"

#pb_falcon :
#        cpus-per-task : 1
#        mem           : "500"
#        time          : "00-00:30:00"
